/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents an access token.
 * @export
 * @interface AccessToken
 */
export interface AccessToken {
    /**
     * The access token.
     * @type {string}
     * @memberof AccessToken
     */
    'access_token': string;
    /**
     * The type of token.
     * @type {string}
     * @memberof AccessToken
     */
    'token_type': string;
    /**
     * The expiration time in seconds.
     * @type {number}
     * @memberof AccessToken
     */
    'expires_in': number;
}

