/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProviderState } from './provider-state';

/**
 * 
 * @export
 * @interface CollectionProviderState
 */
export interface CollectionProviderState {
    /**
     * List of items in the collection.
     * @type {Array<ProviderState>}
     * @memberof CollectionProviderState
     */
    'items'?: Array<ProviderState>;
    /**
     * The number of items in the collection.
     * @type {number}
     * @memberof CollectionProviderState
     */
    'item_count': number;
}

