/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents authors of an entity.
 * @export
 * @interface EntityMultiAuthorRead
 */
export interface EntityMultiAuthorRead {
    /**
     * 
     * @type {string}
     * @memberof EntityMultiAuthorRead
     */
    'primary'?: string | null;
    /**
     * List of additional artists. If none are known, an empty list.
     * @type {Array<string>}
     * @memberof EntityMultiAuthorRead
     */
    'collaborating'?: Array<string>;
}

