/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents the author of an entity.
 * @export
 * @interface EntitySingleAuthorRead
 */
export interface EntitySingleAuthorRead {
    /**
     * 
     * @type {string}
     * @memberof EntitySingleAuthorRead
     */
    'primary'?: string | null;
}

