/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Base class for identifiers of an entity.
 * @export
 * @interface EntityIdentifiersBase
 */
export interface EntityIdentifiersBase {
    /**
     * ID of the entity in the provider\'s database.
     * @type {string}
     * @memberof EntityIdentifiersBase
     */
    'provider_id': string;
}

