/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Data to create a new OAuth2 state.
 * @export
 * @interface OAuth2StateCreate
 */
export interface OAuth2StateCreate {
    /**
     * The redirect URI specified by the client.
     * @type {string}
     * @memberof OAuth2StateCreate
     */
    'redirect_uri': string;
}

