/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information required to insert a track into a playlist.
 * @export
 * @interface PlaylistMultiTrackInsert
 */
export interface PlaylistMultiTrackInsert {
    /**
     * ID of the track to be inserted. Cannot be an empty string.
     * @type {Array<string>}
     * @memberof PlaylistMultiTrackInsert
     */
    'provider_ids': Array<string>;
}

