/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information required to create a new playlist.
 * @export
 * @interface PlaylistCreate
 */
export interface PlaylistCreate {
    /**
     * Title of the playlist. Cannot be an empty string.
     * @type {string}
     * @memberof PlaylistCreate
     */
    'title': string;
}

