/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntityAssetsBase } from './entity-assets-base';
// May contain unused imports in some cases
// @ts-ignore
import type { EntityIdentifiersBase } from './entity-identifiers-base';
// May contain unused imports in some cases
// @ts-ignore
import type { EntityMetaRead } from './entity-meta-read';
// May contain unused imports in some cases
// @ts-ignore
import type { EntitySingleAuthorRead } from './entity-single-author-read';

/**
 * Represents a playlist.
 * @export
 * @interface PlaylistRead
 */
export interface PlaylistRead {
    /**
     * Title of the playlist.
     * @type {string}
     * @memberof PlaylistRead
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof PlaylistRead
     */
    'description'?: string | null;
    /**
     * Indicates if the playlist is public.
     * @type {boolean}
     * @memberof PlaylistRead
     */
    'is_public': boolean;
    /**
     * Author of the playlist.
     * @type {EntitySingleAuthorRead}
     * @memberof PlaylistRead
     */
    'author': EntitySingleAuthorRead;
    /**
     * Meta information of the track.
     * @type {EntityMetaRead}
     * @memberof PlaylistRead
     */
    'meta': EntityMetaRead;
    /**
     * Identifiers of the playlist.
     * @type {EntityIdentifiersBase}
     * @memberof PlaylistRead
     */
    'identifiers': EntityIdentifiersBase;
    /**
     * Assets of the playlist.
     * @type {EntityAssetsBase}
     * @memberof PlaylistRead
     */
    'assets': EntityAssetsBase;
}

