/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PlaylistTaskCreate } from './playlist-task-create';
// May contain unused imports in some cases
// @ts-ignore
import type { PlaylistTaskProgress } from './playlist-task-progress';
// May contain unused imports in some cases
// @ts-ignore
import type { TaskStatus } from './task-status';

/**
 * Status of the playlist transfer.
 * @export
 * @interface PlaylistTaskStatus
 */
export interface PlaylistTaskStatus {
    /**
     * Unique identifier for the task.
     * @type {string}
     * @memberof PlaylistTaskStatus
     */
    'task_id': string;
    /**
     * Current status of the task as a whole.
     * @type {TaskStatus}
     * @memberof PlaylistTaskStatus
     */
    'status': TaskStatus;
    /**
     * 
     * @type {string}
     * @memberof PlaylistTaskStatus
     */
    'status_reason'?: string | null;
    /**
     * Unix timestamp in UTC to help tell when the task was put in the queue.
     * @type {number}
     * @memberof PlaylistTaskStatus
     */
    'queued_at': number;
    /**
     * 
     * @type {number}
     * @memberof PlaylistTaskStatus
     */
    'done_at'?: number | null;
    /**
     * Original request parameters.
     * @type {PlaylistTaskCreate}
     * @memberof PlaylistTaskStatus
     */
    'arguments': PlaylistTaskCreate;
    /**
     * Details about the progress of the task.
     * @type {PlaylistTaskProgress}
     * @memberof PlaylistTaskStatus
     */
    'progress': PlaylistTaskProgress;
}



