/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TrackRead } from './track-read';

/**
 * Current progress of a playlist transfer or sync task.
 * @export
 * @interface PlaylistTaskProgress
 */
export interface PlaylistTaskProgress {
    /**
     * 
     * @type {TrackRead}
     * @memberof PlaylistTaskProgress
     */
    'track'?: TrackRead | null;
    /**
     * How many tracks have been already processed.
     * @type {number}
     * @memberof PlaylistTaskProgress
     */
    'handled'?: number;
    /**
     * How many tracks are in queue to be processed.
     * @type {number}
     * @memberof PlaylistTaskProgress
     */
    'in_queue'?: number;
}

