/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TaskKind } from './task-kind';

/**
 * Playlist transfer parameters.
 * @export
 * @interface PlaylistTaskCreate
 */
export interface PlaylistTaskCreate {
    /**
     * Origin provider for the playlist.
     * @type {string}
     * @memberof PlaylistTaskCreate
     */
    'from_provider': string;
    /**
     * Target provider to replicate the playlist on.
     * @type {string}
     * @memberof PlaylistTaskCreate
     */
    'to_provider': string;
    /**
     * The type of the task.
     * @type {TaskKind}
     * @memberof PlaylistTaskCreate
     */
    'kind': TaskKind;
    /**
     * Source playlist you wish to replicate.
     * @type {string}
     * @memberof PlaylistTaskCreate
     */
    'from_playlist': string;
}



