/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProviderLinkType } from './provider-link-type';

/**
 * 
 * @export
 * @interface ProviderLinkingRead
 */
export interface ProviderLinkingRead {
    /**
     * The type of linking the user has to go through for the provider.
     * @type {ProviderLinkType}
     * @memberof ProviderLinkingRead
     */
    'link_type': ProviderLinkType;
    /**
     * Relevant URL for OAuth2 flow or form submission.
     * @type {string}
     * @memberof ProviderLinkingRead
     */
    'target_url': string;
    /**
     * Whether the provider is linked to the authenticated user.
     * @type {boolean}
     * @memberof ProviderLinkingRead
     */
    'linked': boolean;
}



