/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents the state of a provider.
 * @export
 * @interface ProviderState
 */
export interface ProviderState {
    /**
     * The name of the provider.
     * @type {string}
     * @memberof ProviderState
     */
    'provider_name': string;
    /**
     * Whether the provider is connected (linked) to the authenticated user.
     * @type {boolean}
     * @memberof ProviderState
     */
    'is_connected': boolean;
}

