/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProviderAboutRead } from './provider-about-read';
// May contain unused imports in some cases
// @ts-ignore
import type { ProviderLinkingRead } from './provider-linking-read';

/**
 * Generic, UI display information about a provider.
 * @export
 * @interface ProviderRead
 */
export interface ProviderRead {
    /**
     * The name of the provider.
     * @type {string}
     * @memberof ProviderRead
     */
    'provider_name': string;
    /**
     * Whether the provider was configured.
     * @type {boolean}
     * @memberof ProviderRead
     */
    'is_configured': boolean;
    /**
     * Information about the linking process for the provider.
     * @type {ProviderLinkingRead}
     * @memberof ProviderRead
     */
    'linking': ProviderLinkingRead;
    /**
     * The UI display information about the provider.
     * @type {ProviderAboutRead}
     * @memberof ProviderRead
     */
    'ui': ProviderAboutRead;
}

