/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Generic, UI display information about a provider.
 * @export
 * @interface ProviderAboutRead
 */
export interface ProviderAboutRead {
    /**
     * A description of the provider meant to be used in user facing interfaces.
     * @type {string}
     * @memberof ProviderAboutRead
     */
    'description': string;
    /**
     * The name of the provider meant to be used in user facing interfaces.
     * @type {string}
     * @memberof ProviderAboutRead
     */
    'display_name': string;
    /**
     * The URL to the favicon of the provider.
     * @type {string}
     * @memberof ProviderAboutRead
     */
    'favicon': string;
}

