/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Describes the type of the task.
 * @export
 * @enum {string}
 */

export const TaskKind = {
    PlaylistTransfer: 'playlist_transfer'
} as const;

export type TaskKind = typeof TaskKind[keyof typeof TaskKind];



