/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents common third-party identifiers of a track.
 * @export
 * @interface TrackIdentifiersThirdPartyBase
 */
export interface TrackIdentifiersThirdPartyBase {
    /**
     * 
     * @type {string}
     * @memberof TrackIdentifiersThirdPartyBase
     */
    'isrc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackIdentifiersThirdPartyBase
     */
    'musicbrainz'?: string | null;
}

