/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntityAssetsBase } from './entity-assets-base';
// May contain unused imports in some cases
// @ts-ignore
import type { EntityMetaRead } from './entity-meta-read';
// May contain unused imports in some cases
// @ts-ignore
import type { EntityMultiAuthorRead } from './entity-multi-author-read';
// May contain unused imports in some cases
// @ts-ignore
import type { TrackIdentifiersRead } from './track-identifiers-read';

/**
 * Represents a track.
 * @export
 * @interface TrackRead
 */
export interface TrackRead {
    /**
     * Title of the track.
     * @type {string}
     * @memberof TrackRead
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof TrackRead
     */
    'album_name': string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackRead
     */
    'duration'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrackRead
     */
    'track_number'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrackRead
     */
    'release_year'?: number | null;
    /**
     * Authors of the track.
     * @type {EntityMultiAuthorRead}
     * @memberof TrackRead
     */
    'author': EntityMultiAuthorRead;
    /**
     * Identifiers of the track.
     * @type {TrackIdentifiersRead}
     * @memberof TrackRead
     */
    'identifiers': TrackIdentifiersRead;
    /**
     * Assets of the track.
     * @type {EntityAssetsBase}
     * @memberof TrackRead
     */
    'assets': EntityAssetsBase;
    /**
     * Meta information of the track.
     * @type {EntityMetaRead}
     * @memberof TrackRead
     */
    'meta': EntityMetaRead;
}

