/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntityAssetsBase } from './entity-assets-base';
// May contain unused imports in some cases
// @ts-ignore
import type { EntityMultiAuthorRead } from './entity-multi-author-read';
// May contain unused imports in some cases
// @ts-ignore
import type { TrackIdentifiersThirdPartyBase } from './track-identifiers-third-party-base';

/**
 * Metadata that can be used to match a track.
 * @export
 * @interface TrackMatchCreate
 */
export interface TrackMatchCreate {
    /**
     * Title of the track.
     * @type {string}
     * @memberof TrackMatchCreate
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof TrackMatchCreate
     */
    'album_name': string | null;
    /**
     * 
     * @type {number}
     * @memberof TrackMatchCreate
     */
    'duration'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrackMatchCreate
     */
    'track_number'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrackMatchCreate
     */
    'release_year'?: number | null;
    /**
     * Authors of the track.
     * @type {EntityMultiAuthorRead}
     * @memberof TrackMatchCreate
     */
    'author': EntityMultiAuthorRead;
    /**
     * Identifiers of the track.
     * @type {TrackIdentifiersThirdPartyBase}
     * @memberof TrackMatchCreate
     */
    'identifiers': TrackIdentifiersThirdPartyBase;
    /**
     * Assets of the track.
     * @type {EntityAssetsBase}
     * @memberof TrackMatchCreate
     */
    'assets': EntityAssetsBase;
}

