/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents identifiers of a track.
 * @export
 * @interface TrackIdentifiersRead
 */
export interface TrackIdentifiersRead {
    /**
     * 
     * @type {string}
     * @memberof TrackIdentifiersRead
     */
    'isrc'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrackIdentifiersRead
     */
    'musicbrainz'?: string | null;
    /**
     * ID of the entity in the provider\'s database.
     * @type {string}
     * @memberof TrackIdentifiersRead
     */
    'provider_id': string;
}

