/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents a user creation DTO.
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
    /**
     * Username must be unique and at least 3 characters long.
     * @type {string}
     * @memberof UserCreate
     */
    'username': string;
    /**
     * Password must be at least 8 characters long.
     * @type {string}
     * @memberof UserCreate
     */
    'password': string;
}

