/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents a user response DTO.
 * @export
 * @interface UserRead
 */
export interface UserRead {
    /**
     * User ID
     * @type {number}
     * @memberof UserRead
     */
    'id': number;
    /**
     * Username
     * @type {string}
     * @memberof UserRead
     */
    'username': string;
    /**
     * Whether the user is an admin
     * @type {boolean}
     * @memberof UserRead
     */
    'is_admin'?: boolean;
}

