/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CollectionPlaylistRead } from '../models';
/**
 * LibraryApi - axios parameter creator
 * @export
 */
export const LibraryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Compiles a list of playlists the user owns and has saved to their library across all of their linked providers.  Please note that this endpoint may not return up-to-date data because it relies on caching to prevent excessive API calls.  Notes: - Some providers do not return all playlists (e.g. Spotify\'s automatically generated playlists). - Some providers do not support retrieving playlists that are saved but **not owned** by the linked account (e.g. YouTube). - This endpoint returns all playlists it finds. Checking wether 2 playlists are the same but synced is up to the client.
         * @summary Get the user\'s playlists across all providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLibraryPlaylists: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/library/playlists`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LibraryApi - functional programming interface
 * @export
 */
export const LibraryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LibraryApiAxiosParamCreator(configuration)
    return {
        /**
         * Compiles a list of playlists the user owns and has saved to their library across all of their linked providers.  Please note that this endpoint may not return up-to-date data because it relies on caching to prevent excessive API calls.  Notes: - Some providers do not return all playlists (e.g. Spotify\'s automatically generated playlists). - Some providers do not support retrieving playlists that are saved but **not owned** by the linked account (e.g. YouTube). - This endpoint returns all playlists it finds. Checking wether 2 playlists are the same but synced is up to the client.
         * @summary Get the user\'s playlists across all providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLibraryPlaylists(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CollectionPlaylistRead>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLibraryPlaylists(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LibraryApi.getLibraryPlaylists']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LibraryApi - factory interface
 * @export
 */
export const LibraryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LibraryApiFp(configuration)
    return {
        /**
         * Compiles a list of playlists the user owns and has saved to their library across all of their linked providers.  Please note that this endpoint may not return up-to-date data because it relies on caching to prevent excessive API calls.  Notes: - Some providers do not return all playlists (e.g. Spotify\'s automatically generated playlists). - Some providers do not support retrieving playlists that are saved but **not owned** by the linked account (e.g. YouTube). - This endpoint returns all playlists it finds. Checking wether 2 playlists are the same but synced is up to the client.
         * @summary Get the user\'s playlists across all providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLibraryPlaylists(options?: RawAxiosRequestConfig): AxiosPromise<CollectionPlaylistRead> {
            return localVarFp.getLibraryPlaylists(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LibraryApi - interface
 * @export
 * @interface LibraryApi
 */
export interface LibraryApiInterface {
    /**
     * Compiles a list of playlists the user owns and has saved to their library across all of their linked providers.  Please note that this endpoint may not return up-to-date data because it relies on caching to prevent excessive API calls.  Notes: - Some providers do not return all playlists (e.g. Spotify\'s automatically generated playlists). - Some providers do not support retrieving playlists that are saved but **not owned** by the linked account (e.g. YouTube). - This endpoint returns all playlists it finds. Checking wether 2 playlists are the same but synced is up to the client.
     * @summary Get the user\'s playlists across all providers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LibraryApiInterface
     */
    getLibraryPlaylists(options?: RawAxiosRequestConfig): AxiosPromise<CollectionPlaylistRead>;

}

/**
 * LibraryApi - object-oriented interface
 * @export
 * @class LibraryApi
 * @extends {BaseAPI}
 */
export class LibraryApi extends BaseAPI implements LibraryApiInterface {
    /**
     * Compiles a list of playlists the user owns and has saved to their library across all of their linked providers.  Please note that this endpoint may not return up-to-date data because it relies on caching to prevent excessive API calls.  Notes: - Some providers do not return all playlists (e.g. Spotify\'s automatically generated playlists). - Some providers do not support retrieving playlists that are saved but **not owned** by the linked account (e.g. YouTube). - This endpoint returns all playlists it finds. Checking wether 2 playlists are the same but synced is up to the client.
     * @summary Get the user\'s playlists across all providers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LibraryApi
     */
    public getLibraryPlaylists(options?: RawAxiosRequestConfig) {
        return LibraryApiFp(this.configuration).getLibraryPlaylists(options).then((request) => request(this.axios, this.basePath));
    }
}

