/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * YouTubeApi - axios parameter creator
 * @export
 */
export const YouTubeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Starts the YouTube Authorization Code Flow. Redirects the user to the YouTube authorization page. The user will be asked to log in and authorize the application.  Details: https://developers.google.com/identity/protocols/oauth2  Takes a `state` parameter that includes metadata about the client.
         * @summary Start the YouTube Authorization Code Flow
         * @param {string} state 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signInWithGoogle: async (state: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'state' is not null or undefined
            assertParamExists('signInWithGoogle', 'state', state)
            const localVarPath = `/api/providers/youtube/authorize`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unlinks the Google account associated with the user.
         * @summary Unlink YouTube
         * @param {string} provider 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlinkYouTubeAccount: async (provider: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('unlinkYouTubeAccount', 'provider', provider)
            const localVarPath = `/api/providers/youtube/unlink`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (provider !== undefined) {
                localVarQueryParameter['provider'] = provider;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * YouTubeApi - functional programming interface
 * @export
 */
export const YouTubeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = YouTubeApiAxiosParamCreator(configuration)
    return {
        /**
         * Starts the YouTube Authorization Code Flow. Redirects the user to the YouTube authorization page. The user will be asked to log in and authorize the application.  Details: https://developers.google.com/identity/protocols/oauth2  Takes a `state` parameter that includes metadata about the client.
         * @summary Start the YouTube Authorization Code Flow
         * @param {string} state 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signInWithGoogle(state: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signInWithGoogle(state, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['YouTubeApi.signInWithGoogle']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unlinks the Google account associated with the user.
         * @summary Unlink YouTube
         * @param {string} provider 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unlinkYouTubeAccount(provider: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unlinkYouTubeAccount(provider, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['YouTubeApi.unlinkYouTubeAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * YouTubeApi - factory interface
 * @export
 */
export const YouTubeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = YouTubeApiFp(configuration)
    return {
        /**
         * Starts the YouTube Authorization Code Flow. Redirects the user to the YouTube authorization page. The user will be asked to log in and authorize the application.  Details: https://developers.google.com/identity/protocols/oauth2  Takes a `state` parameter that includes metadata about the client.
         * @summary Start the YouTube Authorization Code Flow
         * @param {string} state 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signInWithGoogle(state: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.signInWithGoogle(state, options).then((request) => request(axios, basePath));
        },
        /**
         * Unlinks the Google account associated with the user.
         * @summary Unlink YouTube
         * @param {string} provider 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlinkYouTubeAccount(provider: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unlinkYouTubeAccount(provider, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * YouTubeApi - interface
 * @export
 * @interface YouTubeApi
 */
export interface YouTubeApiInterface {
    /**
     * Starts the YouTube Authorization Code Flow. Redirects the user to the YouTube authorization page. The user will be asked to log in and authorize the application.  Details: https://developers.google.com/identity/protocols/oauth2  Takes a `state` parameter that includes metadata about the client.
     * @summary Start the YouTube Authorization Code Flow
     * @param {string} state 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YouTubeApiInterface
     */
    signInWithGoogle(state: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Unlinks the Google account associated with the user.
     * @summary Unlink YouTube
     * @param {string} provider 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YouTubeApiInterface
     */
    unlinkYouTubeAccount(provider: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * YouTubeApi - object-oriented interface
 * @export
 * @class YouTubeApi
 * @extends {BaseAPI}
 */
export class YouTubeApi extends BaseAPI implements YouTubeApiInterface {
    /**
     * Starts the YouTube Authorization Code Flow. Redirects the user to the YouTube authorization page. The user will be asked to log in and authorize the application.  Details: https://developers.google.com/identity/protocols/oauth2  Takes a `state` parameter that includes metadata about the client.
     * @summary Start the YouTube Authorization Code Flow
     * @param {string} state 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YouTubeApi
     */
    public signInWithGoogle(state: string, options?: RawAxiosRequestConfig) {
        return YouTubeApiFp(this.configuration).signInWithGoogle(state, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unlinks the Google account associated with the user.
     * @summary Unlink YouTube
     * @param {string} provider 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YouTubeApi
     */
    public unlinkYouTubeAccount(provider: string, options?: RawAxiosRequestConfig) {
        return YouTubeApiFp(this.configuration).unlinkYouTubeAccount(provider, options).then((request) => request(this.axios, this.basePath));
    }
}

