/* tslint:disable */
/* eslint-disable */
/**
 * tunesynctool web API
 * Web API wrapper for the tunesynctool Python package with some extra features.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/authentication-api';
export * from './api/catalog-api';
export * from './api/deezer-api';
export * from './api/library-api';
export * from './api/providers-api';
export * from './api/spotify-api';
export * from './api/subsonic-api';
export * from './api/tasks-api';
export * from './api/users-api';
export * from './api/you-tube-api';

